name: CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
        
  test_pull_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
        
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Pulling image
      # some comment smth again
      run: |
        VERSION='gh_workflow'
        #docker pull ghcr.io/${{ github.actor }}/predict_service:gh_workflow
        echo {{ github.actor }}
        #docker pull ghcr.io/ml-hls-annual-project-cv-4/predict_service:gh_workflow
